-- Database Schema optimized for PostgreSQL (Supabase) based on ERD v1
-- Reordered for Foreign Key Dependency Compatibility

-- 1. INDEPENDENT TABLES (No foreign keys)
CREATE TABLE IF NOT EXISTS BARANGAY_INFO (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    map_geo_json JSONB,
    location_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS NEWSLETTER_SUBSCRIBER (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(120) NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. TABLES WITH DEPENDENCIES

-- "USER" depends only on BARANGAY_INFO. Quoted because it's a reserved keyword.
CREATE TABLE IF NOT EXISTS "USER" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'user',
    barangay_id INTEGER,
    is_approved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (barangay_id) REFERENCES BARANGAY_INFO(id)
);

-- Depends on "USER"
CREATE TABLE IF NOT EXISTS PASSWORD_RESET_TOKEN (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    token VARCHAR(128) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES "USER"(id)
);

-- Depends on "USER" and BARANGAY_INFO
CREATE TABLE IF NOT EXISTS HERITAGE_PROFILE (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_type VARCHAR(50) NOT NULL,
    form_control_number VARCHAR(100),
    name_of_asset VARCHAR(200),
    common_name VARCHAR(200),
    barangay_id INTEGER,
    location_details TEXT,
    contact_person VARCHAR(200),
    contact_number VARCHAR(50),
    ownership_type VARCHAR(50),
    owner_administrator VARCHAR(200),
    usage_status VARCHAR(50),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    significance TEXT,
    conservation_status TEXT,
    mapper_name VARCHAR(200),
    date_profiled DATE,
    status VARCHAR(20) DEFAULT 'pending',
    user_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (barangay_id) REFERENCES BARANGAY_INFO(id),
    FOREIGN KEY (user_id) REFERENCES "USER"(id)
);

-- Depends on BARANGAY_INFO, HERITAGE_PROFILE, and "USER"
CREATE TABLE IF NOT EXISTS ATTRACTION (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    category VARCHAR(50),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    image_url VARCHAR(500),
    barangay_id INTEGER,
    heritage_profile_id INTEGER,
    status VARCHAR(20) DEFAULT 'pending',
    user_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (barangay_id) REFERENCES BARANGAY_INFO(id),
    FOREIGN KEY (heritage_profile_id) REFERENCES HERITAGE_PROFILE(id),
    FOREIGN KEY (user_id) REFERENCES "USER"(id)
);

-- Depends on BARANGAY_INFO and "USER"
CREATE TABLE IF NOT EXISTS EVENT (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    location VARCHAR(255),
    category VARCHAR(50),
    image_url VARCHAR(500),
    barangay_id INTEGER,
    status VARCHAR(20) DEFAULT 'pending',
    user_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (barangay_id) REFERENCES BARANGAY_INFO(id),
    FOREIGN KEY (user_id) REFERENCES "USER"(id)
);

-- Depends on "USER"
CREATE TABLE IF NOT EXISTS GALLERY_ITEM (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    url VARCHAR(500) NOT NULL,
    caption TEXT,
    user_id INTEGER,
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES "USER"(id)
);

CREATE TABLE IF NOT EXISTS ANALYTICS_PAGE_VIEW (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_url VARCHAR(500),
    view_type VARCHAR(50),
    item_id INTEGER,
    page_name VARCHAR(100),
    user_id INTEGER,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    session_id VARCHAR(100),
    ip_address VARCHAR(45),
    device_info TEXT
);

-- Depends on "USER" and ATTRACTION
CREATE TABLE IF NOT EXISTS USER_FAVORITE_ATTRACTION (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    attraction_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES "USER"(id),
    FOREIGN KEY (attraction_id) REFERENCES ATTRACTION(id)
);

-- Depends on "USER" and EVENT
CREATE TABLE IF NOT EXISTS USER_EVENT_INTEREST (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    event_id INTEGER,
    status VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES "USER"(id),
    FOREIGN KEY (event_id) REFERENCES EVENT(id)
);

-- Depends on "USER" and ATTRACTION
CREATE TABLE IF NOT EXISTS ATTRACTION_REVIEW (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    attraction_id INTEGER,
    rating INTEGER,
    comment TEXT,
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES "USER"(id),
    FOREIGN KEY (attraction_id) REFERENCES ATTRACTION(id)
);

-- 3. HERITAGE DETAIL TABLES (All depend on HERITAGE_PROFILE)

CREATE TABLE IF NOT EXISTS BUILT_HERITAGE_DETAIL (
    heritage_profile_id INTEGER PRIMARY KEY,
    type_of_building VARCHAR(100),
    year_constructed INTEGER,
    architect_builder VARCHAR(200),
    architectural_style VARCHAR(100),
    materials_used TEXT,
    state_of_conservation TEXT,
    FOREIGN KEY (heritage_profile_id) REFERENCES HERITAGE_PROFILE(id)
);

CREATE TABLE IF NOT EXISTS MOVABLE_HERITAGE_DETAIL (
    heritage_profile_id INTEGER PRIMARY KEY,
    type_of_object VARCHAR(100),
    material TEXT,
    dimensions VARCHAR(100),
    current_location TEXT,
    state_of_conservation TEXT,
    FOREIGN KEY (heritage_profile_id) REFERENCES HERITAGE_PROFILE(id)
);

CREATE TABLE IF NOT EXISTS NATURAL_HERITAGE_DETAIL (
    heritage_profile_id INTEGER PRIMARY KEY,
    type_of_natural_heritage VARCHAR(100),
    area_size VARCHAR(100),
    primary_features TEXT,
    biodiversity_significance TEXT,
    FOREIGN KEY (heritage_profile_id) REFERENCES HERITAGE_PROFILE(id)
);

CREATE TABLE IF NOT EXISTS INTANGIBLE_HERITAGE_DETAIL (
    heritage_profile_id INTEGER PRIMARY KEY,
    category VARCHAR(100),
    description TEXT,
    practitioners TEXT,
    transmission_mode TEXT,
    FOREIGN KEY (heritage_profile_id) REFERENCES HERITAGE_PROFILE(id)
);

CREATE TABLE IF NOT EXISTS PERSONALITY_DETAIL (
    heritage_profile_id INTEGER PRIMARY KEY,
    full_name VARCHAR(200),
    dates_of_birth_death VARCHAR(100),
    place_of_birth VARCHAR(200),
    major_achievements TEXT,
    FOREIGN KEY (heritage_profile_id) REFERENCES HERITAGE_PROFILE(id)
);

CREATE TABLE IF NOT EXISTS INSTITUTION_DETAIL (
    heritage_profile_id INTEGER PRIMARY KEY,
    type_of_institution VARCHAR(100),
    year_established INTEGER,
    head_of_institution VARCHAR(200),
    activities_services TEXT,
    FOREIGN KEY (heritage_profile_id) REFERENCES HERITAGE_PROFILE(id)
);

CREATE TABLE IF NOT EXISTS LGU_PROGRAM_DETAIL (
    heritage_profile_id INTEGER PRIMARY KEY,
    program_name VARCHAR(200),
    starting_year INTEGER,
    description TEXT,
    culture_projects JSONB,
    FOREIGN KEY (heritage_profile_id) REFERENCES HERITAGE_PROFILE(id)
);
