-- Fix USER_FAVORITE missing columns + any remaining stragglers
-- Run in Supabase SQL Editor

-- 1. USER_FAVORITE — add missing columns (safe even if table was never renamed)
DO $$
BEGIN
    -- If table is still called USER_FAVORITE_ATTRACTION, rename it
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'USER_FAVORITE_ATTRACTION')
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'USER_FAVORITE') THEN
        ALTER TABLE "USER_FAVORITE_ATTRACTION" RENAME TO "USER_FAVORITE";
    END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

ALTER TABLE "USER_FAVORITE" ADD COLUMN IF NOT EXISTS establishment_id INTEGER;
ALTER TABLE "USER_FAVORITE" ADD COLUMN IF NOT EXISTS event_id INTEGER;
ALTER TABLE "USER_FAVORITE" ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active';

-- 2. REVIEW — same issue: old ATTRACTION_REVIEW may exist under old name
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'ATTRACTION_REVIEW')
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'REVIEW') THEN
        ALTER TABLE "ATTRACTION_REVIEW" RENAME TO "REVIEW";
    END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "REVIEW" (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES "USER"(id),
    attraction_id INTEGER REFERENCES "ATTRACTION"(id),
    establishment_id INTEGER,
    rating INTEGER,
    comment TEXT,
    status VARCHAR(20) DEFAULT 'pending',
    parent_id INTEGER REFERENCES "REVIEW"(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    photo_urls JSONB DEFAULT '[]'::jsonb
);

-- 3. MAP_FEEDBACK
CREATE TABLE IF NOT EXISTS "MAP_FEEDBACK" (
    id SERIAL PRIMARY KEY,
    attraction_id INTEGER REFERENCES "ATTRACTION"(id),
    feedback_type VARCHAR(50),
    message TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Ensure ANNOUNCEMENT table exists (was causing "relation does not exist")
CREATE TABLE IF NOT EXISTS "ANNOUNCEMENT" (
    id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    user_id INTEGER REFERENCES "USER"(id),
    barangay_id INTEGER REFERENCES "BARANGAY_INFO"(id),
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. USER — reset_token columns
ALTER TABLE "USER" ADD COLUMN IF NOT EXISTS reset_token VARCHAR(128) UNIQUE;
ALTER TABLE "USER" ADD COLUMN IF NOT EXISTS reset_token_expires_at TIMESTAMP;
ALTER TABLE "USER" ADD COLUMN IF NOT EXISTS reset_token_used BOOLEAN DEFAULT FALSE;

-- 6. ATTRACTION — missing columns
ALTER TABLE "ATTRACTION" ADD COLUMN IF NOT EXISTS directions TEXT;
ALTER TABLE "ATTRACTION" ADD COLUMN IF NOT EXISTS osm_alternatives JSONB;
ALTER TABLE "ATTRACTION" ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;
ALTER TABLE "ATTRACTION" ADD COLUMN IF NOT EXISTS physical_status VARCHAR(50);
ALTER TABLE "ATTRACTION" ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT TRUE;
ALTER TABLE "ATTRACTION" ADD COLUMN IF NOT EXISTS opening_hours VARCHAR(100);
ALTER TABLE "ATTRACTION" ADD COLUMN IF NOT EXISTS entrance_fee VARCHAR(100);
ALTER TABLE "ATTRACTION" ADD COLUMN IF NOT EXISTS contact_info VARCHAR(100);
ALTER TABLE "ATTRACTION" ADD COLUMN IF NOT EXISTS facilities TEXT;
ALTER TABLE "ATTRACTION" ADD COLUMN IF NOT EXISTS advisory_message TEXT;
ALTER TABLE "ATTRACTION" ADD COLUMN IF NOT EXISTS advisory_status VARCHAR(20);
ALTER TABLE "ATTRACTION" ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- 7. EVENT — missing columns
ALTER TABLE "EVENT" ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE "EVENT" ADD COLUMN IF NOT EXISTS date TIMESTAMP;
ALTER TABLE "EVENT" ADD COLUMN IF NOT EXISTS latitude FLOAT;
ALTER TABLE "EVENT" ADD COLUMN IF NOT EXISTS longitude FLOAT;
ALTER TABLE "EVENT" ADD COLUMN IF NOT EXISTS end_date TIMESTAMP;
ALTER TABLE "EVENT" ADD COLUMN IF NOT EXISTS max_participants INTEGER;
ALTER TABLE "EVENT" ADD COLUMN IF NOT EXISTS is_virtual BOOLEAN DEFAULT FALSE;
ALTER TABLE "EVENT" ADD COLUMN IF NOT EXISTS virtual_link VARCHAR(500);
ALTER TABLE "EVENT" ADD COLUMN IF NOT EXISTS contact_person VARCHAR(200);
ALTER TABLE "EVENT" ADD COLUMN IF NOT EXISTS contact_number VARCHAR(50);
ALTER TABLE "EVENT" ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;
ALTER TABLE "EVENT" ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "EVENT" ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- 8. BARANGAY_INFO — missing columns
ALTER TABLE "BARANGAY_INFO" ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES "USER"(id);
ALTER TABLE "BARANGAY_INFO" ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- 9. HERITAGE_PROFILE — missing columns
ALTER TABLE "HERITAGE_PROFILE" ADD COLUMN IF NOT EXISTS form_data JSONB;
ALTER TABLE "HERITAGE_PROFILE" ADD COLUMN IF NOT EXISTS template_slug VARCHAR(100);
ALTER TABLE "HERITAGE_PROFILE" ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "HERITAGE_PROFILE" ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- 10. ESTABLISHMENT — missing columns
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS barangay_id INTEGER REFERENCES "BARANGAY_INFO"(id);
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS email VARCHAR(120);
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS website VARCHAR(300);
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS operating_hours JSONB;
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS price_range VARCHAR(20);
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS amenities JSONB;
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS cover_image_url VARCHAR(500);
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS logo_url VARCHAR(500);
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES "USER"(id);
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'pending';
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS rating_avg FLOAT DEFAULT 0;
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS review_count INTEGER DEFAULT 0;
ALTER TABLE "ESTABLISHMENT" ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- 11. Sub-tables for ESTABLISHMENT
CREATE TABLE IF NOT EXISTS "ESTABLISHMENT_ROOM" (
    id SERIAL PRIMARY KEY,
    establishment_id INTEGER REFERENCES "ESTABLISHMENT"(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price_per_night FLOAT,
    capacity INTEGER DEFAULT 2,
    amenities JSONB,
    image_urls JSONB,
    is_available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ESTABLISHMENT_MENU_ITEM" (
    id SERIAL PRIMARY KEY,
    establishment_id INTEGER REFERENCES "ESTABLISHMENT"(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    price FLOAT,
    category VARCHAR(50) DEFAULT 'main',
    image_url VARCHAR(500),
    is_available BOOLEAN DEFAULT TRUE,
    is_bestseller BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "BUSINESS_VERIFICATION" (
    id SERIAL PRIMARY KEY,
    establishment_id INTEGER REFERENCES "ESTABLISHMENT"(id) ON DELETE CASCADE,
    document_url VARCHAR(500) NOT NULL,
    document_type VARCHAR(50),
    status VARCHAR(20) DEFAULT 'pending',
    reviewed_by INTEGER REFERENCES "USER"(id),
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 12. Notification tables
CREATE TABLE IF NOT EXISTS "NEWSLETTER_SUBSCRIBER" (
    id SERIAL PRIMARY KEY,
    email VARCHAR(120) UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    user_id INTEGER REFERENCES "USER"(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "NEWSLETTER_HISTORY" (
    id SERIAL PRIMARY KEY,
    subject VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    recipient_count INTEGER DEFAULT 0,
    sender_id INTEGER REFERENCES "USER"(id) ON DELETE SET NULL,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "USER_NOTIFICATION" (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES "USER"(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    link VARCHAR(200),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 13. Gamification tables
CREATE TABLE IF NOT EXISTS "ACHIEVEMENT_BADGE" (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    badge_image_url VARCHAR(500),
    required_visits INTEGER DEFAULT 1,
    target_locations JSONB NOT NULL,
    reward_promo JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "USER_PASSPORT" (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES "USER"(id) ON DELETE CASCADE,
    badge_id INTEGER REFERENCES "ACHIEVEMENT_BADGE"(id) ON DELETE CASCADE,
    unlocked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "TOURIST_CHECK_IN" (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES "USER"(id),
    attraction_id INTEGER REFERENCES "ATTRACTION"(id),
    establishment_id INTEGER REFERENCES "ESTABLISHMENT"(id),
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    distance_meters FLOAT,
    verified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 14. Chat tables
CREATE TABLE IF NOT EXISTS "CHAT_ROOM" (
    id SERIAL PRIMARY KEY,
    type VARCHAR(20) DEFAULT 'general',
    barangay_id INTEGER REFERENCES "BARANGAY_INFO"(id),
    establishment_id INTEGER REFERENCES "ESTABLISHMENT"(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "CHAT_PARTICIPANT" (
    id SERIAL PRIMARY KEY,
    chat_room_id INTEGER REFERENCES "CHAT_ROOM"(id),
    user_id INTEGER REFERENCES "USER"(id),
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_read_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "CHAT_MESSAGE" (
    id SERIAL PRIMARY KEY,
    chat_room_id INTEGER REFERENCES "CHAT_ROOM"(id),
    sender_id INTEGER REFERENCES "USER"(id),
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_system_msg BOOLEAN DEFAULT FALSE
);

-- 15. Booking tables
CREATE TABLE IF NOT EXISTS "BOOKABLE_ASSET" (
    id SERIAL PRIMARY KEY,
    attraction_id INTEGER REFERENCES "ATTRACTION"(id) ON DELETE CASCADE,
    heritage_profile_id INTEGER REFERENCES "HERITAGE_PROFILE"(id) ON DELETE CASCADE,
    daily_capacity INTEGER DEFAULT 50,
    requires_approval BOOLEAN DEFAULT TRUE,
    booking_instructions TEXT,
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "BOOKING_SLOT" (
    id SERIAL PRIMARY KEY,
    bookable_asset_id INTEGER REFERENCES "BOOKABLE_ASSET"(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    total_capacity INTEGER NOT NULL,
    booked_count INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "RESERVATION" (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES "USER"(id),
    booking_slot_id INTEGER REFERENCES "BOOKING_SLOT"(id) ON DELETE CASCADE,
    party_size INTEGER DEFAULT 1 NOT NULL,
    primary_contact VARCHAR(100),
    special_requests TEXT,
    status VARCHAR(20) DEFAULT 'pending',
    qr_code_token VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 16. Analytics — missing columns + new tables
ALTER TABLE "ANALYTICS_PAGE_VIEW" ADD COLUMN IF NOT EXISTS view_type VARCHAR(50);
ALTER TABLE "ANALYTICS_PAGE_VIEW" ADD COLUMN IF NOT EXISTS item_id INTEGER;
ALTER TABLE "ANALYTICS_PAGE_VIEW" ADD COLUMN IF NOT EXISTS page_name VARCHAR(100);

CREATE TABLE IF NOT EXISTS "DATABASE_AUDIT_LOG" (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES "USER"(id),
    action VARCHAR(50) NOT NULL,
    table_name VARCHAR(100) NOT NULL,
    record_id INTEGER,
    ip_address VARCHAR(45),
    user_agent VARCHAR(500),
    query_summary VARCHAR(500),
    status VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "VISITOR_LOG" (
    id SERIAL PRIMARY KEY,
    target_type VARCHAR(50) NOT NULL,
    target_id INTEGER NOT NULL,
    visitor_count INTEGER DEFAULT 1 NOT NULL,
    visitor_name VARCHAR(150),
    visitor_age INTEGER,
    visitor_address VARCHAR(255),
    is_system_user BOOLEAN DEFAULT FALSE,
    visit_date DATE DEFAULT CURRENT_DATE,
    logged_by INTEGER REFERENCES "USER"(id),
    visitor_user_id INTEGER REFERENCES "USER"(id),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 17. Gallery — missing columns
ALTER TABLE "GALLERY_ITEM" ADD COLUMN IF NOT EXISTS item_id INTEGER;
ALTER TABLE "GALLERY_ITEM" ADD COLUMN IF NOT EXISTS attraction_id INTEGER REFERENCES "ATTRACTION"(id);
ALTER TABLE "GALLERY_ITEM" ADD COLUMN IF NOT EXISTS heritage_profile_id INTEGER REFERENCES "HERITAGE_PROFILE"(id);
ALTER TABLE "GALLERY_ITEM" ADD COLUMN IF NOT EXISTS event_id INTEGER REFERENCES "EVENT"(id);
ALTER TABLE "GALLERY_ITEM" ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- 18. Indexes
CREATE INDEX IF NOT EXISTS idx_user_email ON "USER"(email);
CREATE INDEX IF NOT EXISTS idx_user_reset_token ON "USER"(reset_token);
CREATE INDEX IF NOT EXISTS idx_attraction_status ON "ATTRACTION"(status);
CREATE INDEX IF NOT EXISTS idx_review_attraction ON "REVIEW"(attraction_id);
CREATE INDEX IF NOT EXISTS idx_review_user ON "REVIEW"(user_id);
CREATE INDEX IF NOT EXISTS idx_event_date ON "EVENT"(date);
CREATE INDEX IF NOT EXISTS idx_establishment_owner ON "ESTABLISHMENT"(owner_id);
CREATE INDEX IF NOT EXISTS idx_establishment_status ON "ESTABLISHMENT"(status);
CREATE INDEX IF NOT EXISTS idx_announcement_status ON "ANNOUNCEMENT"(status);
CREATE INDEX IF NOT EXISTS idx_chat_message_room ON "CHAT_MESSAGE"(chat_room_id);
CREATE INDEX IF NOT EXISTS idx_reservation_user ON "RESERVATION"(user_id);
CREATE INDEX IF NOT EXISTS idx_booking_slot_date ON "BOOKING_SLOT"(date);
