-- Fix existing REVIEW table missing columns
-- The old ATTRACTION_REVIEW was renamed but has wrong schema
ALTER TABLE "REVIEW" ADD COLUMN IF NOT EXISTS establishment_id INTEGER;
ALTER TABLE "REVIEW" ADD COLUMN IF NOT EXISTS parent_id INTEGER REFERENCES "REVIEW"(id);
ALTER TABLE "REVIEW" ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "REVIEW" ADD COLUMN IF NOT EXISTS photo_urls JSONB DEFAULT '[]'::jsonb;

-- Also ensure USER_FAVORITE has all columns
ALTER TABLE "USER_FAVORITE" ADD COLUMN IF NOT EXISTS establishment_id INTEGER;
ALTER TABLE "USER_FAVORITE" ADD COLUMN IF NOT EXISTS event_id INTEGER;
ALTER TABLE "USER_FAVORITE" ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active';
