"""add detailed visitor fields

Revision ID: 1857056725af
Revises: c4feb793ada6
Create Date: 2026-05-16 10:45:23.360887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1857056725af'
down_revision = 'c4feb793ada6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VISITOR_LOG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('visitor_age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visitor_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_system_user', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VISITOR_LOG', schema=None) as batch_op:
        batch_op.drop_column('is_system_user')
        batch_op.drop_column('visitor_address')
        batch_op.drop_column('visitor_age')
        batch_op.drop_column('visitor_name')

    # ### end Alembic commands ###
