"""add form_data

Revision ID: 536847569d90
Revises: 72e1f5a11684
Create Date: 2026-05-24 16:59:26.040511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '536847569d90'
down_revision = '72e1f5a11684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    tables_to_drop = [
        'INSTITUTION_DETAIL',
        'INTANGIBLE_HERITAGE_DETAIL',
        'LGU_PROGRAM_DETAIL',
        'BUILT_HERITAGE_DETAIL',
        'PERSONALITY_DETAIL',
        'NATURAL_HERITAGE_DETAIL',
        'MOVABLE_HERITAGE_DETAIL'
    ]
    
    for table_name in tables_to_drop:
        # Standardize matching to case-insensitive to be safe
        matching_tables = [t for t in tables if t.upper() == table_name.upper()]
        if matching_tables:
            op.drop_table(matching_tables[0])
            
    with op.batch_alter_table('ESTABLISHMENT_REVIEW', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_est_review_parent', 'ESTABLISHMENT_REVIEW', ['parent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('HERITAGE_PROFILE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_data', sa.JSON(), nullable=True))

    with op.batch_alter_table('MAP_FEEDBACK', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_foreign_key(None, 'ATTRACTION', ['attraction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MAP_FEEDBACK', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('HERITAGE_PROFILE', schema=None) as batch_op:
        batch_op.drop_column('form_data')

    with op.batch_alter_table('ESTABLISHMENT_REVIEW', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ESTABLISHMENT_REVIEW', ['parent_id'], ['id'])

    op.create_table('MOVABLE_HERITAGE_DETAIL',
    sa.Column('heritage_profile_id', sa.INTEGER(), nullable=False),
    sa.Column('type_of_object', sa.VARCHAR(length=100), nullable=True),
    sa.Column('material', sa.TEXT(), nullable=True),
    sa.Column('dimensions', sa.VARCHAR(length=100), nullable=True),
    sa.Column('current_location', sa.TEXT(), nullable=True),
    sa.Column('state_of_conservation', sa.TEXT(), nullable=True),
    sa.Column('meta_data', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['heritage_profile_id'], ['HERITAGE_PROFILE.id'], ),
    sa.PrimaryKeyConstraint('heritage_profile_id')
    )
    op.create_table('NATURAL_HERITAGE_DETAIL',
    sa.Column('heritage_profile_id', sa.INTEGER(), nullable=False),
    sa.Column('type_of_natural_heritage', sa.VARCHAR(length=100), nullable=True),
    sa.Column('area_size', sa.VARCHAR(length=100), nullable=True),
    sa.Column('primary_features', sa.TEXT(), nullable=True),
    sa.Column('biodiversity_significance', sa.TEXT(), nullable=True),
    sa.Column('meta_data', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['heritage_profile_id'], ['HERITAGE_PROFILE.id'], ),
    sa.PrimaryKeyConstraint('heritage_profile_id')
    )
    op.create_table('PERSONALITY_DETAIL',
    sa.Column('heritage_profile_id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('dates_of_birth_death', sa.VARCHAR(length=100), nullable=True),
    sa.Column('place_of_birth', sa.VARCHAR(length=200), nullable=True),
    sa.Column('major_achievements', sa.TEXT(), nullable=True),
    sa.Column('meta_data', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['heritage_profile_id'], ['HERITAGE_PROFILE.id'], ),
    sa.PrimaryKeyConstraint('heritage_profile_id')
    )
    op.create_table('BUILT_HERITAGE_DETAIL',
    sa.Column('heritage_profile_id', sa.INTEGER(), nullable=False),
    sa.Column('type_of_building', sa.VARCHAR(length=100), nullable=True),
    sa.Column('year_constructed', sa.INTEGER(), nullable=True),
    sa.Column('architect_builder', sa.VARCHAR(length=200), nullable=True),
    sa.Column('architectural_style', sa.VARCHAR(length=100), nullable=True),
    sa.Column('materials_used', sa.TEXT(), nullable=True),
    sa.Column('state_of_conservation', sa.TEXT(), nullable=True),
    sa.Column('meta_data', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['heritage_profile_id'], ['HERITAGE_PROFILE.id'], ),
    sa.PrimaryKeyConstraint('heritage_profile_id')
    )
    op.create_table('LGU_PROGRAM_DETAIL',
    sa.Column('heritage_profile_id', sa.INTEGER(), nullable=False),
    sa.Column('program_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('starting_year', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('culture_projects', sqlite.JSON(), nullable=True),
    sa.Column('meta_data', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['heritage_profile_id'], ['HERITAGE_PROFILE.id'], ),
    sa.PrimaryKeyConstraint('heritage_profile_id')
    )
    op.create_table('INTANGIBLE_HERITAGE_DETAIL',
    sa.Column('heritage_profile_id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('practitioners', sa.TEXT(), nullable=True),
    sa.Column('transmission_mode', sa.TEXT(), nullable=True),
    sa.Column('meta_data', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['heritage_profile_id'], ['HERITAGE_PROFILE.id'], ),
    sa.PrimaryKeyConstraint('heritage_profile_id')
    )
    op.create_table('INSTITUTION_DETAIL',
    sa.Column('heritage_profile_id', sa.INTEGER(), nullable=False),
    sa.Column('type_of_institution', sa.VARCHAR(length=100), nullable=True),
    sa.Column('year_established', sa.INTEGER(), nullable=True),
    sa.Column('head_of_institution', sa.VARCHAR(length=200), nullable=True),
    sa.Column('activities_services', sa.TEXT(), nullable=True),
    sa.Column('meta_data', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['heritage_profile_id'], ['HERITAGE_PROFILE.id'], ),
    sa.PrimaryKeyConstraint('heritage_profile_id')
    )
    # ### end Alembic commands ###
