"""Initial migration

Revision ID: 5cce0fb12628
Revises: 
Create Date: 2026-01-18 20:11:40.597988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cce0fb12628'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attraction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attraction_barangay'), ['barangay'], unique=False)
        batch_op.create_index(batch_op.f('ix_attraction_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_attraction_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attraction_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_attraction_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attraction_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attraction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attraction_user_id'))
        batch_op.drop_index(batch_op.f('ix_attraction_status'))
        batch_op.drop_index(batch_op.f('ix_attraction_name'))
        batch_op.drop_index(batch_op.f('ix_attraction_created_at'))
        batch_op.drop_index(batch_op.f('ix_attraction_category'))
        batch_op.drop_index(batch_op.f('ix_attraction_barangay'))

    # ### end Alembic commands ###
