"""Add booking models

Revision ID: 72e1f5a11684
Revises: 782bb68165dd
Create Date: 2026-05-21 22:16:12.175398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e1f5a11684'
down_revision = '782bb68165dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ESTABLISHMENT_REVIEW', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ESTABLISHMENT_REVIEW_establishment_id'), ['establishment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ESTABLISHMENT_REVIEW_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ESTABLISHMENT_REVIEW_user_id'), ['user_id'], unique=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'ESTABLISHMENT_REVIEW', ['parent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('USER_NOTIFICATION', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_USER_NOTIFICATION_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_USER_NOTIFICATION_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_USER_NOTIFICATION_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER_NOTIFICATION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_NOTIFICATION_user_id'))
        batch_op.drop_index(batch_op.f('ix_USER_NOTIFICATION_is_read'))
        batch_op.drop_index(batch_op.f('ix_USER_NOTIFICATION_created_at'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ESTABLISHMENT_REVIEW', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ESTABLISHMENT_REVIEW', ['parent_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_ESTABLISHMENT_REVIEW_user_id'))
        batch_op.drop_index(batch_op.f('ix_ESTABLISHMENT_REVIEW_parent_id'))
        batch_op.drop_index(batch_op.f('ix_ESTABLISHMENT_REVIEW_establishment_id'))

    # ### end Alembic commands ###
