"""add parent_id to reviews

Revision ID: 782bb68165dd
Revises: 1857056725af
Create Date: 2026-05-17 23:12:03.142603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '782bb68165dd'
down_revision = '1857056725af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ATTRACTION', schema=None) as batch_op:
        batch_op.drop_column('google_place_id')
        batch_op.drop_column('contact_website')
        batch_op.drop_column('reviews_data')
        batch_op.drop_column('opening_hours')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('rating')
        batch_op.drop_column('images_data')
        batch_op.drop_column('osm_details')

    with op.batch_alter_table('ATTRACTION_REVIEW', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_ATTRACTION_REVIEW_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key('fk_review_parent', 'ATTRACTION_REVIEW', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ATTRACTION_REVIEW', schema=None) as batch_op:
        batch_op.drop_constraint('fk_review_parent', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ATTRACTION_REVIEW_parent_id'))
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('ATTRACTION', schema=None) as batch_op:
        batch_op.add_column(sa.Column('osm_details', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('images_data', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('opening_hours', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('reviews_data', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('contact_website', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('google_place_id', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
