"""Add template_slug and meta_data to heritage models

Revision ID: a66d309ef0e0
Revises: 
Create Date: 2026-05-12 21:58:16.938146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66d309ef0e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BUILT_HERITAGE_DETAIL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=True))

    with op.batch_alter_table('HERITAGE_PROFILE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_slug', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_HERITAGE_PROFILE_template_slug'), ['template_slug'], unique=False)

    with op.batch_alter_table('INSTITUTION_DETAIL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=True))

    with op.batch_alter_table('INTANGIBLE_HERITAGE_DETAIL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=True))

    with op.batch_alter_table('LGU_PROGRAM_DETAIL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=True))

    with op.batch_alter_table('MOVABLE_HERITAGE_DETAIL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=True))

    with op.batch_alter_table('NATURAL_HERITAGE_DETAIL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=True))

    with op.batch_alter_table('PERSONALITY_DETAIL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PERSONALITY_DETAIL', schema=None) as batch_op:
        batch_op.drop_column('meta_data')

    with op.batch_alter_table('NATURAL_HERITAGE_DETAIL', schema=None) as batch_op:
        batch_op.drop_column('meta_data')

    with op.batch_alter_table('MOVABLE_HERITAGE_DETAIL', schema=None) as batch_op:
        batch_op.drop_column('meta_data')

    with op.batch_alter_table('LGU_PROGRAM_DETAIL', schema=None) as batch_op:
        batch_op.drop_column('meta_data')

    with op.batch_alter_table('INTANGIBLE_HERITAGE_DETAIL', schema=None) as batch_op:
        batch_op.drop_column('meta_data')

    with op.batch_alter_table('INSTITUTION_DETAIL', schema=None) as batch_op:
        batch_op.drop_column('meta_data')

    with op.batch_alter_table('HERITAGE_PROFILE', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_HERITAGE_PROFILE_template_slug'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('template_slug')

    with op.batch_alter_table('BUILT_HERITAGE_DETAIL', schema=None) as batch_op:
        batch_op.drop_column('meta_data')

    # ### end Alembic commands ###
