"""Add VisitorLog table

Revision ID: c4feb793ada6
Revises: a66d309ef0e0
Create Date: 2026-05-16 10:25:43.542250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4feb793ada6'
down_revision = 'a66d309ef0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VISITOR_LOG',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('visitor_count', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('logged_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['logged_by'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('VISITOR_LOG', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_VISITOR_LOG_logged_by'), ['logged_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_VISITOR_LOG_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_VISITOR_LOG_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_VISITOR_LOG_visit_date'), ['visit_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VISITOR_LOG', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_VISITOR_LOG_visit_date'))
        batch_op.drop_index(batch_op.f('ix_VISITOR_LOG_target_type'))
        batch_op.drop_index(batch_op.f('ix_VISITOR_LOG_target_id'))
        batch_op.drop_index(batch_op.f('ix_VISITOR_LOG_logged_by'))

    op.drop_table('VISITOR_LOG')
    # ### end Alembic commands ###
