"""add_gamification_tables

Revision ID: ce17e243724a
Revises: 536847569d90
Create Date: 2026-05-29 20:04:32.828558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce17e243724a'
down_revision = '536847569d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PASSWORD_RESET_TOKEN', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PASSWORD_RESET_TOKEN_user_id'))

    op.drop_table('PASSWORD_RESET_TOKEN')
    with op.batch_alter_table('REVIEW_PHOTO', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_REVIEW_PHOTO_review_id'))

    op.drop_table('REVIEW_PHOTO')
    with op.batch_alter_table('NEWSLETTER_HISTORY', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_NEWSLETTER_HISTORY_sender_id'), ['sender_id'], unique=False)
        batch_op.create_foreign_key(None, 'USER', ['sender_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('NEWSLETTER_SUBSCRIBER', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_NEWSLETTER_SUBSCRIBER_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'USER', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('REVIEW', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_urls', sa.JSON(), nullable=True))

    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_token_used', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reset_token_used')
        batch_op.drop_column('reset_token_expires_at')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('REVIEW', schema=None) as batch_op:
        batch_op.drop_column('photo_urls')

    with op.batch_alter_table('NEWSLETTER_SUBSCRIBER', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_NEWSLETTER_SUBSCRIBER_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('NEWSLETTER_HISTORY', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_NEWSLETTER_HISTORY_sender_id'))
        batch_op.drop_column('sender_id')

    op.create_table('REVIEW_PHOTO',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('review_id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['ATTRACTION_REVIEW.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('REVIEW_PHOTO', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_REVIEW_PHOTO_review_id'), ['review_id'], unique=False)

    op.create_table('PASSWORD_RESET_TOKEN',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=128), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('PASSWORD_RESET_TOKEN', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PASSWORD_RESET_TOKEN_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
