export const MANGATAREM_BARANGAYS = [
  "Andangin",
  "Arellano Street (Poblacion)",
  "Bantay",
  "Bantocaling",
  "Baracbac",
  "Peania Pedania (Bedania)",
  "Bogtong Bolo",
  "Bogtong Bunao",
  "Bogtong Centro",
  "Bogtong Niog",
  "Bogtong Silag",
  "Buaya",
  "Buenlag",
  "Bueno",
  "Bunagan",
  "Bunlalacao",
  "Burgos Street (Poblacion)",
  "Cabaluyan 1st",
  "Cabaluyan 2nd",
  "Cabarabuan",
  "Cabaruan",
  "Cabayaoasan",
  "Cabayugan",
  "Cacaoiten",
  "Calomboyan Norte",
  "Calomboyan Sur",
  "Calvo (Poblacion)",
  "Casilagan",
  "Catarataraan",
  "Caturay Norte",
  "Caturay Sur",
  "Caviernesan",
  "Dorongan Ketaket",
  "Dorongan Linmansangan",
  "Dorongan Punta",
  "Dorongan Sawat",
  "Dorongan Valerio",
  "General Luna (Poblacion)",
  "Historia",
  "Lawak Langka",
  "Linmansangan",
  "Lopez (Poblacion)",
  "Mabini (Poblacion)",
  "Macarang",
  "Malabobo",
  "Malibong",
  "Malunec",
  "Maravilla (Poblacion)",
  "Maravilla-Arellano Ext. (Pob)",
  "Muelang",
  "Naguilayan East",
  "Naguilayan West",
  "Nancasalan Cabison-Bulaney-Niog",
  "Olegario-Caoile (Poblacion)",
  "Olo Cacamposan",
  "Olo Cafabrosan",
  "Olo Cagarlitan",
  "Osmeña (Poblacion)",
  "Pacalat",
  "Pampano",
  "Parian",
  "Paul",
  "Pogon-Aniat",
  "Pogon-Lomboy (Poblacion)",
  "Ponglo-Baleg",
  "Ponglo-Muelag",
  "Quetegan",
  "Quezon (Poblacion)",
  "Salavante",
  "Sapang",
  "Sonson Ongkit",
  "Suaco",
  "Tagac",
  "Takipan",
  "Talogtog",
  "Tococ Barikir",
  "Torre 1st",
  "Torre 2nd",
  "Torres Bugallon (Poblacion)",
  "Umangan",
  "Zamora (Poblacion)",
] as const;

export const AUTH_ROLES = [
  {
    id: "user",
    title: "Explorer",
    subtitle: "Tourist / Visitor",
    description:
      "Unveil Mangatarem's heritage locations, explore interactive maps, view upcoming cultural events, and review establishments.",
    badge: "Public Access",
  },
  {
    id: "contributor",
    title: "Heritage Guardian",
    subtitle: "Barangay Representative / Steward",
    description:
      "Curate historical registers, document local cultural heritage, update mapping layers, and manage events within your barangay's jurisdiction.",
    badge: "Verification Required",
  },
  {
    id: "business_owner",
    title: "Merchant",
    subtitle: "Business Owner",
    description:
      "Showcase your local hotel, inn, transient house, or restaurant. Manage menus, room details, contact parameters, and map pins.",
    badge: "Verification Required",
  },
] as const;
