-- MIGRATION: Sync Local Models to Supabase (FIXED FOR QUOTED IDENTIFIERS)
-- Target: Supabase / PostgreSQL

-- 1. ADD MISSING COLUMNS TO EXISTING TABLES (QUOTED)
DO $$ 
BEGIN 
    -- "ATTRACTION"
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ATTRACTION' AND column_name = 'is_featured' AND table_schema = 'public') THEN
        ALTER TABLE "ATTRACTION" ADD COLUMN is_featured BOOLEAN DEFAULT FALSE;
    END IF;

    -- "EVENT"
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'EVENT' AND column_name = 'latitude' AND table_schema = 'public') THEN
        ALTER TABLE "EVENT" ADD COLUMN latitude DOUBLE PRECISION;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'EVENT' AND column_name = 'longitude' AND table_schema = 'public') THEN
        ALTER TABLE "EVENT" ADD COLUMN longitude DOUBLE PRECISION;
    END IF;

    -- "BARANGAY_INFO"
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'BARANGAY_INFO' AND column_name = 'mission' AND table_schema = 'public') THEN
        ALTER TABLE "BARANGAY_INFO" ADD COLUMN mission TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'BARANGAY_INFO' AND column_name = 'vision' AND table_schema = 'public') THEN
        ALTER TABLE "BARANGAY_INFO" ADD COLUMN vision TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'BARANGAY_INFO' AND column_name = 'history' AND table_schema = 'public') THEN
        ALTER TABLE "BARANGAY_INFO" ADD COLUMN history TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'BARANGAY_INFO' AND column_name = 'cultural_assets' AND table_schema = 'public') THEN
        ALTER TABLE "BARANGAY_INFO" ADD COLUMN cultural_assets TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'BARANGAY_INFO' AND column_name = 'traditions' AND table_schema = 'public') THEN
        ALTER TABLE "BARANGAY_INFO" ADD COLUMN traditions TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'BARANGAY_INFO' AND column_name = 'local_practices' AND table_schema = 'public') THEN
        ALTER TABLE "BARANGAY_INFO" ADD COLUMN local_practices TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'BARANGAY_INFO' AND column_name = 'unique_features' AND table_schema = 'public') THEN
        ALTER TABLE "BARANGAY_INFO" ADD COLUMN unique_features TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'BARANGAY_INFO' AND column_name = 'user_id' AND table_schema = 'public') THEN
        ALTER TABLE "BARANGAY_INFO" ADD COLUMN user_id INTEGER REFERENCES "USER"(id);
    END IF;

    -- "ANALYTICS_PAGE_VIEW"
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ANALYTICS_PAGE_VIEW' AND column_name = 'view_type' AND table_schema = 'public') THEN
        ALTER TABLE "ANALYTICS_PAGE_VIEW" ADD COLUMN view_type VARCHAR(50);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ANALYTICS_PAGE_VIEW' AND column_name = 'item_id' AND table_schema = 'public') THEN
        ALTER TABLE "ANALYTICS_PAGE_VIEW" ADD COLUMN item_id INTEGER;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ANALYTICS_PAGE_VIEW' AND column_name = 'page_name' AND table_schema = 'public') THEN
        ALTER TABLE "ANALYTICS_PAGE_VIEW" ADD COLUMN page_name VARCHAR(100);
    END IF;
END $$;

-- 2. CREATE MISSING TABLES (QUOTED)
CREATE TABLE IF NOT EXISTS "DATABASE_AUDIT_LOG" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES "USER"(id),
    action VARCHAR(50) NOT NULL,
    table_name VARCHAR(100) NOT NULL,
    record_id INTEGER,
    ip_address VARCHAR(45),
    user_agent VARCHAR(500),
    query_summary VARCHAR(500),
    status VARCHAR(20) DEFAULT 'success',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ESTABLISHMENT" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(30) NOT NULL,
    description TEXT,
    address VARCHAR(500),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    barangay_id INTEGER REFERENCES "BARANGAY_INFO"(id),
    contact_number VARCHAR(50),
    email VARCHAR(120),
    website VARCHAR(300),
    operating_hours JSONB,
    price_range VARCHAR(20),
    amenities JSONB,
    cover_image_url VARCHAR(500),
    logo_url VARCHAR(500),
    owner_id INTEGER NOT NULL REFERENCES "USER"(id),
    status VARCHAR(20) DEFAULT 'pending',
    is_featured BOOLEAN DEFAULT FALSE,
    rating_avg DOUBLE PRECISION DEFAULT 0,
    review_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ESTABLISHMENT_ROOM" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id INTEGER NOT NULL REFERENCES "ESTABLISHMENT"(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price_per_night DECIMAL(10,2),
    capacity INTEGER DEFAULT 2,
    amenities JSONB,
    image_urls JSONB,
    is_available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ESTABLISHMENT_MENU_ITEM" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id INTEGER NOT NULL REFERENCES "ESTABLISHMENT"(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    price DECIMAL(10,2),
    category VARCHAR(50),
    image_url VARCHAR(500),
    is_available BOOLEAN DEFAULT TRUE,
    is_bestseller BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ESTABLISHMENT_REVIEW" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "USER"(id),
    establishment_id INTEGER NOT NULL REFERENCES "ESTABLISHMENT"(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
