/**
 * Bundled local photos for Mangatarem attractions.
 *
 * Keys are attraction names (normalized: lowercase). Every path below points
 * at a real file in frontend/public/img (verified). Centralized so landing
 * page, map, and attraction cards resolve the same way.
 */

/** Substring keys matched against attraction names. */
export const PLACE_IMAGE_LOOKUP: Record<string, string> = {
  manleluag: "/img/manleluag_spring.webp",
  "daang kalikasan": "/img/daang_kalikasan.webp",
  "st. raymund": "/img/st_raymund_church.webp",
  "penafort church": "/img/attractions/saint_raymund_de_penafort_parish_church/image_1.jpg",
  timmanguyob: "/img/attractions/timmanguyob_falls/image_1.jpg",
  pacalat: "/img/attractions/pacalat_river/image_1.jpg",
  canding: "/img/attractions/canding_falls/image_1.jpg",
  "kanding": "/img/attractions/canding_falls/image_1.jpg",
  "town plaza": "/img/attractions/municipal_hall/image_1.jpg",
  "municipal hall": "/img/attractions/municipal_hall/image_1.jpg",
  "municipal town plaza": "/img/attractions/municipal_hall/image_1.jpg",
  "aviles residence": "/img/attractions/aviles_residence/image_1.jpg",
  "corleto residence": "/img/attractions/corleto_residence/image_1.jpg",
  "don ramon ventenilla": "/img/attractions/don_ramon_ventenilla_residence/image_1.jpg",
  "ventenilla residence": "/img/attractions/don_ramon_ventenilla_residence/image_1.jpg",
  "dr. jose rizal": "/img/attractions/dr_jose_rizal_monument/image_1.png",
  "jose rizal monument": "/img/attractions/dr_jose_rizal_monument/image_1.png",
  "old convent": "/img/attractions/old_convent/image_1.png",
  "teraoka farm": "/img/attractions/teraoka_farm/image_1.jpg",
  "heritage museum": "/img/attractions/heritage_museum.png",
  "malabobo century": "/img/attractions/malabobo_century_tree.png",
  "malabobo heritage": "/img/attractions/malabobo_heritage.png",
  "st raymund parish": "/img/attractions/st_raymund_parish.png",
};

/** Basenames of every bundled local image (used to validate /img paths). */
export const LOCAL_ASSET_EXISTS = new Set<string>([
  // Top-level /img
  "daang_kalikasan.png", "daang_kalikasan.webp",
  "manleluag_spring.png", "manleluag_spring.webp",
  "st_raymund_church.png", "st_raymund_church.webp",
  "mangatarem_map_teaser.png", "mangatarem_map_teaser.webp",
  "hero.webp", "hero_original.jpg",
  "error-403.png", "error-403.webp",
  "error-404.png", "error-404.webp",
  "icon-192.png", "icon-512.png",
  "car-icon.png",
  // /img/attractions
  "heritage_museum.png", "malabobo_century_tree.png", "malabobo_heritage.png",
  "st_raymund_parish.png", "timmanguyob_falls.png",
  "aviles_residence/image_1.jpg", "aviles_residence/image_2.jpg", "aviles_residence/image_3.jpg",
  "aviles_residence/image_4.jpg", "aviles_residence/image_5.jpg", "aviles_residence/image_6.jpg",
  "canding_falls/image_1.jpg", "canding_falls/image_2.jpg",
  "corleto_residence/image_1.jpg", "corleto_residence/image_2.jpg", "corleto_residence/image_3.jpg",
  "corleto_residence/image_4.jpg", "corleto_residence/image_5.jpg", "corleto_residence/image_6.jpg",
  "daang_kalikasan/image_1.jpg", "daang_kalikasan/image_2.jpg", "daang_kalikasan/image_3.jpg",
  "daang_kalikasan/image_4.jpg", "daang_kalikasan/image_5.jpg",
  "don_ramon_ventenilla_residence/image_1.jpg", "don_ramon_ventenilla_residence/image_2.jpg",
  "don_ramon_ventenilla_residence/image_3.jpg", "don_ramon_ventenilla_residence/image_4.jpg",
  "don_ramon_ventenilla_residence/image_5.jpg", "don_ramon_ventenilla_residence/image_6.jpg",
  "dr_jose_rizal_monument/image_1.png", "dr_jose_rizal_monument/image_2.png",
  "manleluag_spring_protected_landscape/image_1.jpg",
  "manleluag_spring_protected_landscape/image_2.jpg",
  "manleluag_spring_protected_landscape/image_3.jpg",
  "manleluag_spring_protected_landscape/image_4.jpg",
  "manleluag_spring_protected_landscape/image_5.jpg",
  "manleluag_spring_protected_landscape/image_6.jpg",
  "manleluag_spring_protected_landscape/image_7.jpg",
  "municipal_hall/image_1.jpg", "municipal_hall/image_2.jpg",
  "old_convent/image_1.png", "old_convent/image_2.png",
  "pacalat_river/image_1.jpg", "pacalat_river/image_2.jpg", "pacalat_river/image_3.jpg",
  "pacalat_river/image_4.jpg", "pacalat_river/image_5.jpg",
  "saint_raymund_de_peafort_parish_church/image_1.jpg",
  "saint_raymund_de_peafort_parish_church/image_2.jpg",
  "saint_raymund_de_peafort_parish_church/image_3.jpg",
  "saint_raymund_de_peafort_parish_church/image_4.jpg",
  "saint_raymund_de_peafort_parish_church/image_5.jpg",
  "saint_raymund_de_peafort_parish_church/image_6.jpg",
  "saint_raymund_de_peafort_parish_church/image_7.jpg",
  "saint_raymund_de_peafort_parish_church/image_8.jpg",
  "saint_raymund_de_peafort_parish_church/image_9.png",
  "saint_raymund_de_peafort_parish_church/image_10.png",
  "saint_raymund_de_penafort_parish_church/image_1.jpg",
  "saint_raymund_de_penafort_parish_church/image_2.jpg",
  "saint_raymund_de_penafort_parish_church/image_3.jpg",
  "saint_raymund_de_penafort_parish_church/image_4.jpg",
  "saint_raymund_de_penafort_parish_church/image_5.png",
  "teraoka_farm/image_1.jpg", "teraoka_farm/image_2.jpg", "teraoka_farm/image_3.jpg",
  "teraoka_farm/image_4.jpg", "teraoka_farm/image_5.jpg", "teraoka_farm/image_6.jpg",
  "teraoka_farm/image_7.jpg", "teraoka_farm/image_8.jpg", "teraoka_farm/image_9.jpg",
  "teraoka_farm/image_10.jpg", "teraoka_farm/image_11.jpg", "teraoka_farm/image_12.jpg",
  "teraoka_farm/image_13.jpg", "teraoka_farm/image_14.jpg", "teraoka_farm/image_15.jpg",
  "timmanguyob_falls/image_1.jpg", "timmanguyob_falls/image_2.png", "timmanguyob_falls/image_3.jpg",
]);
